### ISSUE TITLE
java.util.ConcurrentModificationException during analysis

### ISSUE THREAD

**Issue by 0xquad** [find-sec-bugs/find-sec-bugs#184] opened 2016-03-30 16:10 UTC
Multiple `ConcurrentModificationException` errors occurred during the analysis of 6 jar files. Snippet below, more complete trace in attached text file. Reported after the analysis, which was completed nonetheless. Might or might not be related to FindSecBugs per se. I can submit the full error report privately if needed. This was a one-time scan, haven't tried to reproduce it.

```
The following errors occurred during analysis:
  Exception while analyzing com.<redacted>(Ljava/util/zip/ZipOutputStream;Ljava/lang/String;Ljava/io/File;)V
    java.util.ConcurrentModificationException
      At java.util.HashMap$HashIterator.nextEntry(Unknown Source)
      At java.util.HashMap$KeyIterator.next(Unknown Source)
      At com.h3xstream.findsecbugs.injection.AbstractInjectionDetector.checkTaintSink(AbstractInjectionDetector.java:111)
      At com.h3xstream.findsecbugs.injection.AbstractInjectionDetector.analyzeLocation(AbstractInjectionDetector.java:81)
      At com.h3xstream.findsecbugs.injection.AbstractTaintDetector.analyzeMethod(AbstractTaintDetector.java:91)
      At com.h3xstream.findsecbugs.injection.AbstractTaintDetector.visitClassContext(AbstractTaintDetector.java:60)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
      At edu.umd.cs.findbugs.gui2.BugLoader.doAnalysis(BugLoader.java:101)
      At edu.umd.cs.findbugs.gui2.AnalyzingDialog$AnalysisThread.run(AnalyzingDialog.java:275)
  Exception while analyzing com.<redacted>(Ljava/lang/String;Ljava/util/Hashtable;)Lcom/<redacted>;
    java.util.ConcurrentModificationException
      At java.util.HashMap$HashIterator.nextEntry(Unknown Source)
...
```

[multiple-errors.txt](https://github.com/find-sec-bugs/find-sec-bugs/files/195932/multiple-errors.txt)

**Comment by h3xstream** [comment] 2016-03-30 19:27
It is seems to be related to : #175

**Comment by h3xstream** [comment] 2016-05-30 23:10
@formanek It seems that `injectionSinks` and `sinkTaints` would need to be synchronized.

**Comment by h3xstream** [comment] 2016-05-31 18:58
@0xquad I am not able to reproduce the specific condition but I can provide you a preliminary version.

In what context did Findbugs was run? (IntelliJ, SonarSource, Ant, Maven, etc.)
And what version was used?

Thanks

**Comment by formanek** [comment] 2016-05-31 19:15
@h3xstream I remember I was fixing this long time ago (after release of 1.4.5, but before this issue was actually reported). I think synchronization is not needed, the exception was thrown by fail-fast iterator during direct modification of a collection (in the same thread).

**Comment by 0xquad** [comment] 2016-05-31 19:30
Do you still need my input for further investigation, or does it mean it's already fixed? Version used was findsecbugs-plugin-1.4.4.jar

**Comment by h3xstream** [comment] 2016-05-31 20:15
@formanek Thanks. closing..

@0xquad Are you using the plugin in an IDE? / Btw. I will notify you when a new release is publish.

**Closed by h3xstream** 2016-05-31 20:15 UTC
Labels: bug

**Comment by 0xquad** [comment] 2016-05-31 22:06
Was the standalone version.
