### ISSUE TITLE
FindSecBugs plugin crash in Intellij

### ISSUE THREAD

**Issue by mcwww** [find-sec-bugs/find-sec-bugs#167] opened 2016-01-15 19:41 UTC
When running new version of FindSecBugs 1.4.5 plugin in Intellij, I obtain the following error:

```java
java/util/Objects
java.lang.NoClassDefFoundError: java/util/Objects
	at com.h3xstream.findsecbugs.taintanalysis.Taint.<init>(Taint.java:89)
	at com.h3xstream.findsecbugs.taintanalysis.TaintMethodSummary.<clinit>(TaintMethodSummary.java:40)
	at com.h3xstream.findsecbugs.taintanalysis.TaintMethodSummaryMap.putFromLine(TaintMethodSummaryMap.java:77)
	at com.h3xstream.findsecbugs.taintanalysis.TaintMethodSummaryMap.load(TaintMethodSummaryMap.java:57)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.loadMethodSummaries(TaintDataflowEngine.java:90)
	at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.<init>(TaintDataflowEngine.java:78)
	at com.h3xstream.findsecbugs.taintanalysis.EngineRegistrar.registerAnalysisEngines(EngineRegistrar.java:32)
	at edu.umd.cs.findbugs.FindBugs2.registerPluginAnalysisEngines(FindBugs2.java:633)
	at edu.umd.cs.findbugs.FindBugs2.createAnalysisCache(FindBugs2.java:594)
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:211)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.asyncStart(FindBugsStarter.java:167)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter.access$000(FindBugsStarter.java:58)
	at org.twodividedbyzero.idea.findbugs.core.FindBugsStarter$1.run(FindBugsStarter.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.ClassNotFoundException: java.util.Objects
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 28 more
```

I am forced to use al old version of FindSecBugs in Intellij.

**Comment by h3xstream** [comment] 2016-05-09 22:04
It seems to be fixed in the current version.
I am not able to reproduce with 1.4.6-SNAPSHOT.

I will notify you when the plugin gets release.

**Closed by h3xstream** 2016-05-09 22:04 UTC
Labels: bug
